ip: localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ip}:3306/umi_system
    username: root
    password: root
  main:
    banner-mode: off
  servlet:
    multipart:
      # 设置上传文件上限
      max-file-size: 20MB
      max-request-size: 20MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志标准输出
  mapper-locations: com/dyuloon/mapper/xml/*.xml
  global-config:
    banner: off
    db-config:
      id-type: auto # 数据库自增策略
server:
  port: 8080
