export const DEFAULT_NAME = 'Umi Max';

/** 通用状态码 */
export type Status = 0 | 1;

//工作台状态
import { MenuCategory } from '@/types/workcenter';
export const WORK_CENTER_MENUS: MenuCategory[] = [
  {
    id: '1xt-master',
    name: '主体业务',
    key: 'master',
    icon: 'AppstoreOutlined',
    subModules: [
      {
        id: '0_ReportQuery',
        name: '报告查询',
        description: '医疗报告查询和管理系统',
        port: 3001,
        icon: 'FileSearchOutlined',
      },
      {
        id: '1_SettleMgmt',
        name: '结算管理',
        description: '医疗费用结算管理系统',
        port: 3002,
        icon: 'DollarOutlined',
      },
      {
        id: '2_DealerSettle',
        name: '经销商结算',
        description: '经销商费用结算系统',
        port: 3003,
        icon: 'ShopOutlined',
      },
      {
        id: '3_NucleicMobile',
        name: '核酸移动',
        description: '核酸检测移动端管理',
        port: 3004,
        icon: 'MobileOutlined',
      },
      {
        id: '4_TransCenter',
        name: '转运中心',
        description: '样本转运中心管理',
        port: 3005,
        icon: 'SendOutlined',
      },
      {
        id: '5_MobileTrans',
        name: '移动转运',
        description: '移动端转运管理系统',
        port: 3006,
        icon: 'CarOutlined',
      },
      {
        id: '6_PretreatWS',
        name: '预处理工作站',
        description: '样本预处理工作站',
        port: 3007,
        icon: 'ExperimentOutlined',
      },
      {
        id: '7_SpecPretreatWS',
        name: '特殊预处理工作站',
        description: '特殊样本预处理工作站',
        port: 3008,
        icon: 'ExperimentOutlined',
      },
      {
        id: '8_RoutineTestWS',
        name: '常规检验工作站',
        description: '常规检验工作站管理',
        port: 3009,
        icon: 'MedicineBoxOutlined',
      },
      {
        id: '9_ELISAMgmt',
        name: 'ELISA管理',
        description: 'ELISA检测管理系统',
        port: 3010,
        icon: 'RadarChartOutlined',
      },
      {
        id: '10_SpecTestWS',
        name: '特检工作站',
        description: '特殊检验工作站',
        port: 3011,
        icon: 'BugOutlined',
      },
      {
        id: '11_SampleMgmtWS',
        name: '样本管理工作站',
        description: '样本管理工作站系统',
        port: 3012,
        icon: 'DatabaseOutlined',
      },
      {
        id: '12_EnvHygiene',
        name: '环境卫生',
        description: '环境卫生监测管理',
        port: 3013,
        icon: 'EnvironmentOutlined',
      },
      {
        id: '13_MicroTestWS',
        name: '微生物检验工作站',
        description: '微生物检验工作站',
        port: 3014,
        icon: 'BugOutlined',
      },
      {
        id: '14_MicroRule',
        name: '微生物规则',
        description: '微生物检验规则管理',
        port: 3015,
        icon: 'SettingOutlined',
      },
      {
        id: '15_BloodTrans',
        name: '输血管理',
        description: '输血管理系统',
        port: 3016,
        icon: '#icon-chanpinbeijing1',
      },
    ],
  },
  {
    id: '2xt-sample',
    name: '样本管理',
    key: 'sample',
    icon: 'ExperimentOutlined',
    subModules: [
      {
        id: 'P3SampleMgmt',
        name: 'P3样本管理',
        description: 'P3级别样本管理系统',
        port: 3101,
        icon: 'ExperimentOutlined',
      },
    ],
  },
  {
    id: '3xt-quality',
    name: '质量控制',
    key: 'quality',
    icon: 'SafetyOutlined',
    subModules: [
      {
        id: '1-PerfValidation',
        name: '性能验证',
        description: '设备性能验证管理',
        port: 3201,
        icon: 'SettingOutlined',
      },
      {
        id: '2-SmartQC_Mgmt',
        name: '智能质控管理',
        description: '智能质控管理系统',
        port: 3202,
        icon: 'RadarChartOutlined',
      },
      {
        id: '3-MobileAvg_PBRTQC',
        name: '移动平均PBRT质控',
        description: '移动平均PBRT质控系统',
        port: 3203,
        icon: 'MobileOutlined',
      },
      {
        id: '4-EQA_Workstation',
        name: 'EQA工作站',
        description: '室间质评工作站',
        port: 3204,
        icon: 'ExperimentOutlined',
      },
      {
        id: '5-ComparisonWS',
        name: '比对工作站',
        description: '检验结果比对工作站',
        port: 3205,
        icon: 'ExperimentOutlined',
      },
      {
        id: '6-GluComparisonWS',
        name: '血糖比对工作站',
        description: '血糖检测比对工作站',
        port: 3206,
        icon: 'MedicineBoxOutlined',
      },
      {
        id: '7-BloodGasComp_Mgmt',
        name: '血气比对管理',
        description: '血气分析比对管理',
        port: 3207,
        icon: 'MedicineBoxOutlined',
      },
      {
        id: '8-RegSampleComp_Mgmt',
        name: '常规样本比对管理',
        description: '常规样本检测比对管理',
        port: 3208,
        icon: 'DatabaseOutlined',
      },
      {
        id: '9-POCT_Mgmt_Center',
        name: 'POCT管理中心',
        description: 'POCT设备管理中心',
        port: 3209,
        icon: 'SettingOutlined',
      },
    ],
  },
  {
    id: '4xt-bi-analytics',
    name: 'BI分析',
    key: 'bi',
    icon: 'BarChartOutlined',
    subModules: [
      {
        id: '1-DataWash_Mgmt',
        name: '数据清洗管理',
        description: '数据清洗和预处理管理',
        port: 3301,
        icon: 'DatabaseOutlined',
      },
      {
        id: '2-SmartDocs',
        name: '智能文档',
        description: '智能文档生成和管理',
        port: 3302,
        icon: 'FileOutlined',
      },
      {
        id: '3-SmartReportPlatform',
        name: '智能报告平台',
        description: '智能报告生成平台',
        port: 3303,
        icon: 'BarChartOutlined',
      },
      {
        id: '4-LabReportCenter',
        name: '实验室报告中心',
        description: '实验室报告管理中心',
        port: 3304,
        icon: 'FileSearchOutlined',
      },
      {
        id: '5-OpControlWS_Screen',
        name: '运营控制工作站大屏',
        description: '运营控制大屏展示',
        port: 3305,
        icon: 'MonitorOutlined',
      },
      {
        id: '6-ISO15189ReportPlatform',
        name: 'ISO15189报告平台',
        description: 'ISO15189标准报告平台',
        port: 3306,
        icon: 'SafetyCertificateOutlined',
      },
      {
        id: '7-BIAnalysis',
        name: 'BI分析',
        description: '商业智能数据分析',
        port: 3307,
        icon: 'BarChartOutlined',
      },
      {
        id: '8-AUGS',
        name: 'AUGS',
        description: '自动化指导系统',
        port: 3308,
        icon: 'RobotOutlined',
      },
      {
        id: '9-QualityIndexMgmtWS',
        name: '质量指标管理工作站',
        description: '质量指标管理工作站',
        port: 3309,
        icon: 'SettingOutlined',
      },
      {
        id: '10-QualityIndexStats_Report_Archiving',
        name: '质量指标统计报告归档',
        description: '质量指标统计报告归档系统',
        port: 3310,
        icon: 'FileOutlined',
      },
    ],
  },
  {
    id: '5xt-lab',
    name: '实验室管理',
    key: 'lab',
    icon: 'ExperimentOutlined',
    subModules: [
      {
        id: '1-StaffMgmt',
        name: '人员管理',
        description: '实验室人员管理系统',
        port: 3401,
        icon: 'UserOutlined',
      },
      {
        id: '2-EquipmentMgmt',
        name: '设备管理',
        description: '实验室设备管理系统',
        port: 3402,
        icon: 'ToolOutlined',
      },
      {
        id: '3-SmartScheduling',
        name: '智能排班',
        description: '实验室智能排班系统',
        port: 3403,
        icon: 'CalendarOutlined',
      },
      {
        id: '4-ExamMgmt1',
        name: '考试管理1',
        description: '人员考试管理系统1',
        port: 3404,
        icon: 'FileTextOutlined',
      },
      {
        id: '5-ExamMgmt2',
        name: '考试管理2',
        description: '人员考试管理系统2',
        port: 3405,
        icon: 'FileTextOutlined',
      },
      {
        id: '6-PaperMarkingMgmt',
        name: '阅卷管理',
        description: '考试阅卷管理系统',
        port: 3406,
        icon: 'EditOutlined',
      },
      {
        id: '7-WrongQuestionMgmt',
        name: '错题管理',
        description: '考试错题管理系统',
        port: 3407,
        icon: 'ExclamationCircleOutlined',
      },
      {
        id: '8-ArchiveCenter',
        name: '档案中心',
        description: '实验室档案管理中心',
        port: 3408,
        icon: 'FileOutlined',
      },
      {
        id: '9-AffairMgmt',
        name: '事务管理',
        description: '实验室事务管理系统',
        port: 3409,
        icon: 'SettingOutlined',
      },
      {
        id: '10-PostAffair',
        name: '岗位事务',
        description: '岗位事务管理系统',
        port: 3410,
        icon: 'UserOutlined',
      },
      {
        id: '11-LabAffairArchiving',
        name: '实验室事务归档',
        description: '实验室事务归档系统',
        port: 3411,
        icon: 'FileOutlined',
      },
      {
        id: '12-AffairHistoryRecords',
        name: '事务历史记录',
        description: '事务历史记录管理',
        port: 3412,
        icon: 'HistoryOutlined',
      },
      {
        id: '13-AdverseEventMgmt',
        name: '不良事件管理',
        description: '实验室不良事件管理',
        port: 3413,
        icon: 'ExclamationCircleOutlined',
      },
      {
        id: '14-TempHumidityMgmt',
        name: '温湿度管理',
        description: '实验室温湿度监控管理',
        port: 3414,
        icon: 'DashboardOutlined',
      },
      {
        id: '15-MaterialsMgmt',
        name: '物料管理',
        description: '实验室物料管理系统',
        port: 3415,
        icon: 'InboxOutlined',
      },
      {
        id: '16-MobileMaterialsMgmt',
        name: '移动物料管理',
        description: '移动端物料管理系统',
        port: 3416,
        icon: 'MobileOutlined',
      },
      {
        id: '17-DocMgmt',
        name: '文档管理',
        description: '实验室文档管理系统',
        port: 3417,
        icon: 'FileOutlined',
      },
      {
        id: '18-SupplierMgmt',
        name: '供应商管理',
        description: '实验室供应商管理系统',
        port: 3418,
        icon: 'ShopOutlined',
      },
      {
        id: '19-EnvMgmt',
        name: '环境管理',
        description: '实验室环境管理系统',
        port: 3419,
        icon: 'EnvironmentOutlined',
      },
      {
        id: '20-InspectionMgmt',
        name: '检查管理',
        description: '实验室检查管理系统',
        port: 3420,
        icon: 'AuditOutlined',
      },
      {
        id: '21-InspectionMgmt',
        name: '检查管理',
        description: '实验室检查管理系统',
        port: 3421,
        icon: 'AuditOutlined',
      },
      {
        id: '22-RiskMgmt',
        name: '风险管理',
        description: '实验室风险管理系统',
        port: 3422,
        icon: 'SafetyOutlined',
      },
      {
        id: '23-MeetingMgmt1',
        name: '会议管理1',
        description: '实验室会议管理系统1',
        port: 3423,
        icon: 'TeamOutlined',
      },
      {
        id: '24-MeetingMgmt2',
        name: '会议管理2',
        description: '实验室会议管理系统2',
        port: 3424,
        icon: 'TeamOutlined',
      },
      {
        id: '25-MeetingMgmt3',
        name: '会议管理3',
        description: '实验室会议管理系统3',
        port: 3425,
        icon: 'TeamOutlined',
      },
      {
        id: '26-StaffEvalMgmt',
        name: '人员评估管理',
        description: '实验室人员评估管理',
        port: 3426,
        icon: 'UserOutlined',
      },
      {
        id: '27-StaffSelfEval',
        name: '人员自评',
        description: '实验室人员自我评估',
        port: 3427,
        icon: 'UserOutlined',
      },
      {
        id: '28-ExpertEval',
        name: '专家评估',
        description: '实验室专家评估系统',
        port: 3428,
        icon: 'CrownOutlined',
      },
      {
        id: '29-LabEnvMgmtSystem',
        name: '实验室环境管理系统',
        description: '实验室环境综合管理系统',
        port: 3429,
        icon: 'EnvironmentOutlined',
      },
    ],
  },
  {
    id: '6xt-knowledge',
    name: '知识库',
    key: 'knowledge',
    icon: 'BookOutlined',
    subModules: [
      {
        id: 'InspectionKnowledgeBase',
        name: '检验知识库',
        description: '医学检验知识库系统',
        port: 3601,
        icon: 'BookOutlined',
      },
    ],
  },
  {
    id: '7xt-samples-lib',
    name: '样本库',
    key: 'sampleslib',
    icon: 'DatabaseOutlined',
    subModules: [
      {
        id: 'ResearchVisitWS',
        name: '科研访问工作站',
        description: '科研样本访问工作站',
        port: 3701,
        icon: 'DatabaseOutlined',
      },
    ],
  },
  {
    id: '8xt-outdoor',
    name: '外勤管理',
    key: 'outdoor',
    icon: 'CarOutlined',
    subModules: [
      {
        id: '1-LabDoctorStation',
        name: '实验医生站',
        description: '实验医生工作站',
        port: 3801,
        icon: 'UserOutlined',
      },
      {
        id: '2-LabNurseStation',
        name: '实验护士站',
        description: '实验护士工作站',
        port: 3802,
        icon: 'UserOutlined',
      },
      {
        id: '3-MobileLabNurseStation',
        name: '移动实验护士站',
        description: '移动实验护士工作站',
        port: 3803,
        icon: 'MobileOutlined',
      },
      {
        id: '4-CollectionWS',
        name: '采集工作站',
        description: '样本采集工作站',
        port: 3804,
        icon: 'ExperimentOutlined',
      },
      {
        id: '5-CollectionAppointment',
        name: '采集预约',
        description: '样本采集预约系统',
        port: 3805,
        icon: 'CalendarOutlined',
      },
    ],
  },
  {
    id: '9xt-third-party',
    name: '第三方',
    key: 'thirdparty',
    icon: 'ApiOutlined',
    subModules: [
      {
        id: 'Test',
        name: '测试模块',
        description: '第三方接口测试模块',
        port: 3901,
        icon: 'ApiOutlined',
      },
    ],
  },
  {
    id: '10xt-maintenance',
    name: '维护管理',
    key: 'maintenance',
    icon: 'ToolOutlined',
    subModules: [
      {
        id: '1-SystemMaintenanceMgmt',
        name: '系统维护管理',
        description: '系统维护管理平台',
        port: 4001,
        icon: 'ToolOutlined',
      },
      {
        id: '2-SystemDataMgmt',
        name: '系统数据管理',
        description: '系统数据管理平台',
        port: 4002,
        icon: 'DatabaseOutlined',
      },
      {
        id: '3-SystemDataMgmt',
        name: '系统数据管理',
        description: '系统数据管理平台2',
        port: 4003,
        icon: 'DatabaseOutlined',
      },
      {
        id: '4-SmartReview_AutoReview',
        name: '智能审核自动审核',
        description: '智能审核自动审核系统',
        port: 4004,
        icon: 'RobotOutlined',
      },
      {
        id: '5-ClinicalRatingScaleMgmt',
        name: '临床评分量表管理',
        description: '临床评分量表管理系统',
        port: 4005,
        icon: 'FileTextOutlined',
      },
    ],
  },
  {
    id: '11xt-designer',
    name: '设计器',
    key: 'designer',
    icon: 'DesktopOutlined',
    subModules: [
      {
        id: '1-AffairProcessMgmtPlatform',
        name: '事务处理管理平台',
        description: '事务处理管理平台',
        port: 4101,
        icon: 'SettingOutlined',
      },
      {
        id: '2-DocumentDesigner',
        name: '文档设计器',
        description: '文档设计器工具',
        port: 4102,
        icon: 'DesktopOutlined',
      },
    ],
  },
  {
    id: '12xt-safety',
    name: '生物安全',
    key: 'safety',
    icon: 'SafetyCertificateOutlined',
    subModules: [
      {
        id: '1-BioSafetyRiskAssessment',
        name: '生物安全风险评估',
        description: '生物安全风险评估系统',
        port: 4201,
        icon: 'SafetyOutlined',
      },
      {
        id: '2-RiskAssessmentData',
        name: '风险评估数据',
        description: '风险评估数据管理',
        port: 4202,
        icon: 'DatabaseOutlined',
      },
      {
        id: '3-StaffMgmt',
        name: '人员管理',
        description: '生物安全人员管理',
        port: 4203,
        icon: 'UserOutlined',
      },
      {
        id: '4-EquipmentMgmt',
        name: '设备管理',
        description: '生物安全设备管理',
        port: 4204,
        icon: 'ToolOutlined',
      },
      {
        id: '5-ExamMgmt',
        name: '考试管理',
        description: '生物安全考试管理',
        port: 4205,
        icon: 'FileTextOutlined',
      },
      {
        id: '6-AffairMgmt',
        name: '事务管理',
        description: '生物安全事务管理',
        port: 4206,
        icon: 'SettingOutlined',
      },
      {
        id: '7-DocMgmt',
        name: '文档管理',
        description: '生物安全文档管理',
        port: 4207,
        icon: 'FileOutlined',
      },
      {
        id: '8-InspectionMgmt',
        name: '检查管理',
        description: '生物安全检查管理',
        port: 4208,
        icon: 'AuditOutlined',
      },
      {
        id: '9-ManagementGuidelines',
        name: '管理指南',
        description: '生物安全管理指南',
        port: 4209,
        icon: 'BookOutlined',
      },
      {
        id: '10-BioSampleFullProcess',
        name: '生物样本全流程',
        description: '生物样本全流程管理',
        port: 4210,
        icon: 'ExperimentOutlined',
      },
      {
        id: '11-PathogenMicrobeSample',
        name: '病原微生物样本',
        description: '病原微生物样本管理',
        port: 4211,
        icon: 'BugOutlined',
      },
      {
        id: '12-FilingLab',
        name: '备案实验室',
        description: '实验室备案管理',
        port: 4212,
        icon: 'ExperimentOutlined',
      },
      {
        id: '13-StaffEval',
        name: '人员评估',
        description: '生物安全人员评估',
        port: 4213,
        icon: 'UserOutlined',
      },
      {
        id: '14-PathogenMicrobeLabBioSafetyEvalSystem',
        name: '病原微生物实验室生物安全评估系统',
        description: '病原微生物实验室生物安全评估系统',
        port: 4214,
        icon: 'SafetyOutlined',
      },
      {
        id: '15-PathogenMicrobeLabBioSafetyFilingSystem',
        name: '病原微生物实验室生物安全备案系统',
        description: '病原微生物实验室生物安全备案系统',
        port: 4215,
        icon: 'SafetyCertificateOutlined',
      },
      {
        id: '16-PathogenMicrobeLabBioSafetySupervisionSystem',
        name: '病原微生物实验室生物安全监管系统',
        description: '病原微生物实验室生物安全监管系统',
        port: 4216,
        icon: 'MonitorOutlined',
      },
    ],
  },
  {
    id: '13xt-poct',
    name: 'POCT管理',
    key: 'poct',
    icon: 'MonitorOutlined',
    subModules: [
      {
        id: '1-POCT_Mgmt_Committee',
        name: 'POCT管理委员会',
        description: 'POCT管理委员会系统',
        port: 4301,
        icon: 'TeamOutlined',
      },
      {
        id: '2-ProjectMgmt',
        name: '项目管理',
        description: 'POCT项目管理系统',
        port: 4302,
        icon: 'SettingOutlined',
      },
      {
        id: '3-QC_Overview',
        name: '质控总览',
        description: 'POCT质控总览系统',
        port: 4303,
        icon: 'MonitorOutlined',
      },
    ],
  },
];
