ip: localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ip}:3306/h01
    username: root
    password: root
  main:
    banner-mode: off
  servlet:
    multipart:
      # 设置上传文件上限
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志标准输出
  mapper-locations: classpath:com/dyuloon/mapper/xml/*.xml
  global-config:
    banner: off
    db-config:
      id-type: auto # 数据库自增策略
server:
  port: 8080
